import { ProjectType } from "./project"

export const SCORE_DESCRIPTIONS: Record<ProjectType, {header: string, content: string}[]> = {
    [ProjectType.ANIME]: [
        /*1*/ {header: '差评', content: '糟糕的动画作品，看完纯粹是为了不留遗憾'},
        /*2*/ {header: '较差', content: '动画质量很差，几乎找不到亮点'},
        /*3*/ {header: '一般', content: '整体表现平平，中规中矩的水准'},
        /*4*/ {header: '普通', content: '动画质量普通，勉强及格的水平'},
        /*5*/ {header: '挺好', content: '观看体验不错，有一些亮点'},
        /*6*/ {header: '优良', content: '观看体验良好，有特色和吸引人的地方'},
        /*7*/ {header: '优秀', content: '优秀的动画作品，很推荐观看'},
        /*8*/ {header: '佳作', content: '非常棒的动画，制作和内容都很出色'},
        /*9*/ {header: '殿堂', content: '殿堂级的精彩作品，几乎挑不出缺点'},
        /*10*/{header: '神作', content: '无可挑剔的神作，值得永远铭记'}
    ],
    [ProjectType.GAME]: [
        /*1*/ {header: '差评', content: '糟糕的游戏体验，完全不推荐'},
        /*2*/ {header: '较差', content: '游戏体验很差，找不出什么亮点'},
        /*3*/ {header: '一般', content: '整体体验一般，中规中矩'},
        /*4*/ {header: '普通', content: '游戏质量普通，及格边缘水平'},
        /*5*/ {header: '挺好', content: '游戏体验还不错，值得一试'},
        /*6*/ {header: '优良', content: '游戏体验良好，有特色和亮点'},
        /*7*/ {header: '优秀', content: '游戏体验优秀，很推荐尝试'},
        /*8*/ {header: '佳作', content: '非常棒的游戏，给予极高评价'},
        /*9*/ {header: '殿堂', content: '殿堂级的精品游戏，超高的游戏体验'},
        /*10*/{header: '神作', content: '足以称之为神作的游戏杰作'},
    ],
    [ProjectType.MANGA]: [
        /*1*/ {header: '差评', content: '糟糕的漫画作品，完全不值得一读'},
        /*2*/ {header: '较差', content: '作品质量很差，难以找到亮点'},
        /*3*/ {header: '一般', content: '整体表现一般，中规中矩'},
        /*4*/ {header: '普通', content: '漫画质量普通，及格边缘水平'},
        /*5*/ {header: '挺好', content: '阅读体验还不错，值得一看'},
        /*6*/ {header: '优良', content: '阅读体验良好，有特色和亮点'},
        /*7*/ {header: '优秀', content: '优秀的漫画作品，很推荐阅读'},
        /*8*/ {header: '佳作', content: '非常棒的漫画，给予极高评价'},
        /*9*/ {header: '殿堂', content: '殿堂级的漫画杰作，超高的阅读体验'},
        /*10*/{header: '神作', content: '足以称之为神作的漫画经典'},
    ],
    [ProjectType.NOVEL]: [
        /*1*/ {header: '差评', content: '糟糕的小说作品，完全不值得一读'},
        /*2*/ {header: '较差', content: '作品质量很差，难以找到亮点'},
        /*3*/ {header: '一般', content: '整体表现一般，中规中矩'},
        /*4*/ {header: '普通', content: '小说质量普通，及格边缘水平'},
        /*5*/ {header: '挺好', content: '阅读体验还不错，值得一看'},
        /*6*/ {header: '优良', content: '阅读体验良好，有特色和亮点'},
        /*7*/ {header: '优秀', content: '优秀的小说作品，很推荐阅读'},
        /*8*/ {header: '佳作', content: '非常棒的小说，给予极高评价'},
        /*9*/ {header: '殿堂', content: '殿堂级的小说杰作，超高的阅读体验'},
        /*10*/{header: '神作', content: '足以称之为神作的小说经典'},
    ],
    [ProjectType.MOVIE]: [
        /*1*/ {header: '差评', content: '糟糕的电影，浪费观影时间'},
        /*2*/ {header: '较差', content: '电影质量很差，难以找到亮点'},
        /*3*/ {header: '一般', content: '整体表现一般，中规中矩'},
        /*4*/ {header: '普通', content: '电影质量普通，及格边缘水平'},
        /*5*/ {header: '挺好', content: '观影体验还不错，值得一看'},
        /*6*/ {header: '优良', content: '观影体验良好，有特色和亮点'},
        /*7*/ {header: '优秀', content: '优秀的电影作品，很推荐观看'},
        /*8*/ {header: '佳作', content: '非常棒的电影，给予极高评价'},
        /*9*/ {header: '殿堂', content: '殿堂级的电影杰作，超高的观影体验'},
        /*10*/{header: '神作', content: '足以称之为神作的电影经典'},
    ],
}