version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/reel_hub?schema=public
      - DIRECT_URL=postgresql://postgres:postgres@db:5432/reel_hub?schema=public
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reel_hub
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 